### ISSUE TITLE
Learning Goals are suboptimal

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/curriculum-funar#6]
The learning goals of this curriculum currently do not have any useful names/titles, which renders the table of learning goals useless. Also, it should be adjusted to be similar to other curricula (like DSL or DATA, for example).

**Comment by mikesperber** [comment]
This is because the curriculum predates the current format. We'll address this along with an overall revision, which @larsrh and I have started discussing today.

**Comment by mikesperber** [comment]
Did this over the course of the recent revisions.
